### ISSUE TITLE
API Processing fail when computing large integral

### ISSUE THREAD

**Issue by IonImpulse** [shiftinv/wolframalpha-moresteps#2]
When I enter the integral:
Integrate[((3a t)/(1+t^3)*D[(3a t^2)/(1+t^3),t])-((3a t^2)/(1+t^3)*D[(3a t)/(1+t^3),t]),{t, 0, Infinity}]
I get two errors:

API processing failed:
Error: Response for pod ID 'IndefiniteIntegral' didn't contain any result pods
Try temporarily disabling the "Only request relevant results" option
 
and 

API processing failed:
Error: Response for pod ID 'Input' didn't contain any result pods
Try temporarily disabling the "Only request relevant results" option

I have disabled all options in the extension options and it still does not work.
On Windows 10, Mozilla Firefox Developer Edition 81.0b9 (64-bit)

**Comment by shiftinv** [comment]
I've seen this happen with other queries as well, mainly eigenvalue/eigenvector computations. Considering that all these queries are on the more computationally intensive side of things might indicate a server-side timeout.
Disabling the "Only request relevant results" option is more of a workaround which sometimes works and sometimes doesn't, I've seen it being successful in a few cases but sadly it's rather unreliable.  
The API behavior with your query is particularly odd: the website shows correct results, whereas the API Explorer shows a timeout and the API itself doesn't show either (no timeout and no/incomplete results).

Enabling the `Retrieve results asynchronously` option with your query successfully showed step-by-step solutions for the definite integral for me (also using Firefox Developer Edition v81.0b9), but it seems like they haven't implemented step-by-step solutions for indefinite integrals yet.

I'll see if I can tweak the timing parameters to fix issues with more complicated queries like yours, but sometimes the API just doesn't want to work the way it's expected to. :/

[1]: https://products.wolframalpha.com/api/explorer/

**Comment by shiftinv** [comment]
Alright, I've increased the computation timeouts (e97be24cb40d3a8b848c66e0995e259185c18f7a) - the defaults used by the API are quite low.  
The step-by-step solution of the definite integral for your query should work fine now, but the indefinite integral still doesn't work which seems to be a limitation of Wolfram|Alpha itself.  
[v1.1.0][1] is already out for Firefox (the Chrome Web Store always takes a bit longer).

I'll close this issue as it should be resolved now, let me know if you have any further questions :)

[1]: https://github.com/shiftinv/wolframalpha-moresteps/releases/tag/v1.1.0
