### ISSUE TITLE
API request unsuccessful error

### ISSUE THREAD

**Issue by GaroleAtharva** [shiftinv/wolframalpha-moresteps#7]
Keeps on showing api request unsuccessful error

**Comment by shiftinv** [comment]
I can't reproduce this issue, everything seems to be working alright as far as I can tell.
Does this happen for you with a specific query, or all of them?

**Comment by JulianBuffoni** [comment]
For me too. The problem seems to occur when you use math input instead of natural language.

**Comment by shiftinv** [comment]
I see, thanks for the info! I'll see if I can figure out a nice solution, the query format for math input is quite different to the natural language input.

**Comment by shiftinv** [comment]
Alright, v1.2.1 should hopefully fix this issue and should be out for both platforms now.
I'd be glad to hear if this issue is resolved; let me know if there's anything else.

**Comment by JulianBuffoni** [comment]
It seems to be working. Nice job bro.

**Comment by shiftinv** [comment]
Cool, thanks for letting me know!

**Comment by abbztract** [comment]
Hey, Shift!

I'm still having an issue in this vein for some reason;

"API processing failed:
Error: API error: Invalid appid (code: 1)"

What should I do to alleviate this? I've tried maths as well as Chem inputs to no avail.

**Comment by shiftinv** [comment]
> I'm still having an issue in this vein for some reason;
> 
> "API processing failed: Error: API error: Invalid appid (code: 1)"

Hi! Not sure about that one, the documentation doesn't really say much about it :/ Did you verify the email address of the developer account/Wolfram ID?

(also fwiw, something seems to have changed on the website recently, which breaks the extension in many cases; I'll get an update out later today)
